apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 2
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: ehabrefaat82/udacity-capstone:1.0.202
          ports:
            - containerPort: 8070
