version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.22
jobs:
  test-cluster:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: capstoneEKS
        type: string
    steps:
      - kubernetes/install:
          kubectl-version: v1.22.0
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: capstoneEKS
      - run:
          command: |
            kubectl get services
          name: Test cluster
  build-code:
    docker:
      - image: cimg/openjdk:8.0.345
    working_directory: ~/tmp
    steps:
      - checkout
      - run:
          name: "build"
          command: |
            echo ">---------- build ----------<"
            mvn -B -DskipTests clean package
      - store_artifacts:
          path: target/udacity-capstone-0.0.1-SNAPSHOT.jar
  test-code:
    docker:
      - image: cimg/openjdk:8.0.345
    steps:
      - checkout
      - run:
          name: "test"
          command: |
            echo ">---------- test ----------<"
#            mvn test
  scan-code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "scan"
          command: |
            echo ">---------- TODO scan ----------<"
  package-build:
    docker:
      - image: cimg/openjdk:8.0.345
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "package"
          command: |
            echo ">---------- package ----------<"
            set -ex
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            echo $TAG
            docker build --build-arg build_number="${CIRCLE_BUILD_NUM}" --tag=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:$TAG .
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
            docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:$TAG
  create-eks:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "  create-eks"
          command: |
            echo ">---------- create-eks ----------<"
            echo "EKS should be create on time, to use cloud formation creating the cluster"
            echo ".../project/.crcleci/eks>  ./create-stack.sh capstoneEKS eks-config.yaml"
  deploy-package:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "deploy"
          command: "echo deploy"
  smoke-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "smoke-test"
          command: "echo smoke-test"
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "publish"
          command: "echo publish"
  clean-up:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "clean-up"
          command: "echo clean-up"
workflows:
  default-workflow:
    jobs:
      - test-cluster
      - build-code
      - test-code:
          requires:
            - build-code
      - scan-code:
          requires:
            - test-code
      - package-build:
          requires:
            - scan-code
      - create-eks:
          requires:
            - scan-code
      - deploy-package:
          requires:
            - package-build
            - create-eks
      - smoke-test:
          requires:
            - deploy-package
      - publish:
          requires:
            - smoke-test
      - clean-up:
          requires:
            - publish
