version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.345
    working_directory: ~/tmp
    steps:
      - checkout
      - run:
          name: "build"
          command: |
            echo ">---------- build ----------<"
            mvn -B -DskipTests clean package
      - store_artifacts:
          path: target/udacity-capstone-0.0.1-SNAPSHOT.jar
  test:
    docker:
      - image: cimg/openjdk:8.0.345
    steps:
      - checkout
      - run:
          name: "test"
          command: |
            echo ">---------- test ----------<"
#            mvn test
  scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "scan"
          command: |
            echo ">---------- TODO scan ----------<"
  package:
    docker:
      - image: cimg/openjdk:8.0.345
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "package"
          command: |
            echo ">---------- package ----------<"
            set -ex
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            echo $TAG
            docker build --build-arg build_number="${CIRCLE_BUILD_NUM}" --tag=${DOCKER_USER}/udacity-capstone:$TAG .
            mkdir -p build_output
            docker save ${DOCKER_USER}/udacity-capstone:$TAG --output build_output/${CIRCLE_BUILD_NUM}.tar
#            docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
#            docker push ehabrefaat82/udacity-capstone:$TAG
      - persist_to_workspace:
          root: build_output
          paths:
            - '*.tar'

  push:
    docker:
      - image: cimg/openjdk:8.0.345
    working_directory: ~/project
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: ~/project/workspace
      - run:
          name: "push to hub"
          command: |
            echo ">---------- push ----------<"
            set -ex
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            echo $TAG
            docker load --input build_output/${CIRCLE_BUILD_NUM}.tar
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
            docker push ${DOCKER_USER}/udacity-capstone:$TAG
  create-infra:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "create-infra"
          command: "echo create-infra"
  config-infra:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "config-infra"
          command: "echo config-infra"
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "deploy"
          command: "echo deploy"
  smoke-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "smoke-test"
          command: "echo smoke-test"
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "publish"
          command: "echo publish"
  clean-up:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "clean-up"
          command: "echo clean-up"
workflows:
  default-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - test
      - package:
          requires:
            - scan
      - push:
          requires:
            - package
      - create-infra:
          requires:
            - scan
      - config-infra:
          requires:
            - create-infra
      - deploy:
          requires:
            - config-infra
            - push
      - smoke-test:
          requires:
            - deploy
      - publish:
          requires:
            - smoke-test
      - clean-up:
          requires:
            - publish
