version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.345
    working_directory: ~/tmp
    steps:
      - checkout
      - run:
          name: "build"
          command: |
            echo ">---------- build ----------<"
            mvn -B -DskipTests clean package
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - target
  test:
    docker:
      - image: cimg/openjdk:8.0.345
    steps:
      - checkout
      - run:
          name: "test"
          command: |
            echo ">---------- test ----------<"
#            mvn test
  scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "scan"
          command: |
            echo ">---------- TODO scan ----------<"
  package:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/tmp/workspace
      - run:
          name: "package"
          command: |
            echo ">---------- package ----------<"
            ls ~/tmp/workspace/target
            mvn -B -DskipTests clean package
            docker build --build-arg target=~/tmp/workspace/target --tag=udacity-capstone:1.0 .
  push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "push"
          command: "echo push"
  create-infra:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "create-infra"
          command: "echo create-infra"
  config-infra:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "config-infra"
          command: "echo config-infra"
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "deploy"
          command: "echo deploy"
  smoke-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "smoke-test"
          command: "echo smoke-test"
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "publish"
          command: "echo publish"
  clean-up:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "clean-up"
          command: "echo clean-up"
workflows:
  default-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - test
      - package:
          requires:
            - scan
      - push:
          requires:
            - package
      - create-infra:
          requires:
            - scan
      - config-infra:
          requires:
            - create-infra
      - deploy:
          requires:
            - config-infra
            - push
      - smoke-test:
          requires:
            - deploy
      - publish:
          requires:
            - smoke-test
      - clean-up:
          requires:
            - publish
