apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  namespace: capstone-deployment
  labels:
    app: capstone-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-deployment
  template:
    metadata:
      labels:
        app: capstone-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: capstone
          image: ehabrefaat82/udacity-capstone:1.0.200
          ports:
            - name: http
              containerPort: 8070
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux